name: shopnest
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  badges: ^3.1.2
  carousel_slider: ^5.0.0
  cloudinary_public: ^0.23.1
  dotted_border: ^2.1.0
  file_picker: ^9.2.0
  fl_chart: ^1.0.0
  flutter_rating_bar: ^4.0.1
  http: ^1.3.0
  pay: ^3.2.1
  provider: ^6.1.2
  rename: ^3.0.2
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/applepay.json
    - assets/gpay.json
